### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by roblunx**
Here are a couple of fixes and improvements I've made. Most of it is in ImNodes::Ez and I tried to keep the number of changes to the ImNodes namespace at a minimum. It's only improvements in ImNodes namespace the shouldn't affect any existing code that depends on it.

* Fixed smoother zooming
* Improved right alignment when title is wider than body
* Moving group of selected nodes does not change selection
* Clicking top-most node (as rendered) now selects it, not the bottom-most below it
* Added styling variables and colors (with stacks)
* Custom node rendering in ImNodes::Ez
* Added IsHovered() function to check if node is hovered
* Added support to handle multiple separate canvases by adding a Ez::Context
* Support to color hovered node differently from others
* Split rendering of nodes and connections into two layers

### CODE REVIEW

**Comment by sphaero** [comment]
This is very welcomed! Why hasn't it merged yet? @rokups

**Comment by rokups** [comment]
Branch has conflicts and this is quite some stuff. Ill find time to review it all soon™.

@roblunx could you rebase this branch on to master so there are no merge commits and conflicts? Thanks 🙏🏻

**Comment by rokups** [comment]
I merged all the changes manually as there were conflicts, also had to fix sample application. Amazing changes, thank you very much @roblunx 🙏🏻

**Comment by roblunx** [comment]
Sorry for not responding earlier. I'm not sure I understand fully what you (@rokups) mean by rebasing branch onto master. I thought there would be no problem since I had merged from your upstream repository I forked.

Do you mean that instead of merging from my updated master into my branch I should have rebased my branch onto my own updated master and made the PR from there?

Anyway, I'm glad you could sort it out. I'll keep this in mind until next time.

**Comment by rokups** [comment]
Maybe your PR version was based on a bit older version as github reported conflicts. I did not want to bother you with something that minor so i did conflict resolution myself. Really great changes, you lifted ::Ez namespace from a demo code to something that is wroth supporting as a solution ❤️

**Pull request closed without merging**
