### PR TITLE
correcting issue #19 and Style -> style_

### PR DESCRIPTION
**Pull request by sonoro1234**
Solves issue #19 and also redo `style_` in previous PR for cimgui compatibility.

### CODE REVIEW

**Comment by rokups** [comment]
> style_

Seems to me this should be fixed on cimgui side. I can understand  avoiding use of special syntax as that is tricky to parse, but requiring upstream project to adopt unusual coding style in some places sounds bit much.

**Comment by sonoro1234** [comment]
It is just that Style is used by imnodes that being also C wrapped makes a collision with another Style definition.
I dont mind how it is called.

**Comment by rokups** [comment]
I see. `CanvasStyle` works, yes :+1:

**Comment by sonoro1234** [comment]
Should I do a new PR?

**Comment by rokups** [comment]
No need. You can amend commit in this one, or just push, and i will squash on merge. Whatever is most convenient for you :)

**Comment by sonoro1234** [comment]
done!!

**Pull request merged**
